### ISSUE TITLE
USER_NOT_EXIST on aliyun cr GetAuthorizationToken

### ISSUE THREAD

**Issue by roura356a** [aliyun/aliyun-cli#232]
**Description**:
When using a RAM user account, even with admin privileges to test, when running `aliyun cr GetAuthorizationToken` it fails with the error below. Runs fine when using my Alibaba Cloud root credentials.

**Execution Command**:
`aliyun ram GetAccountAlias`

**Output**:
```
ERROR: SDK.ServerError
ErrorCode:
Recommend:
RequestId:
Message: {"code":"USER_NOT_EXIST","message":"user is not exist.","requestId":"19625155-9EC4-4ACF-953D-DD38F09C9315"}
```

**Comment by domgoer** [comment]
the same issue

**Comment by vanniszsu** [comment]
same issue too

**Comment by domechn** [comment]
@vanniszsu  In my case, my RAM user account did not have access for `cr`. 
The problem was solved when i opened the permissions for the RAM account

**Comment by vanniszsu** [comment]
> @vanniszsu In my case, my RAM user account did not have access for `cr`.
> The problem was solved when i opened the permissions for the RAM account

I got this resolved too,  
in order to make the CR aware of the RAM user,  the RAM user need to be 'registered' to the CR first,  

it means,  
if the RAM user has web console access,  he need to  go the the Repo's 'Access Credential',  set the password first 
if the RAM user is just programmatic without console access,   he need to runAPI: [CreateUserInfo]( https://help.aliyun.com/document_detail/142759.html?spm=a2c4g.11186623.6.619.72d66bbdNAscjT) first
