### ISSUE TITLE
Auto-completion does not work with aliyun CLI even after executing 'aliyun auto-completion' command

### ISSUE THREAD

**Issue by Kahlir** [aliyun/aliyun-cli#247]
Even after executing auto-completion command, aliyun cli doesn't auto complete the commands api names/parameters

OS: macOS Catalina version 10.15.2
Terminal Version: 2.10
Alibaba Cloud Command Line Interface Version 3.0.16

**Comment by night556** [comment]
The tests here are normal. If there is no automatic completion, it may be because the configuration file written with the completion command has not been correctly loaded by the system. Please confirm that the completion command statement has been correctly written to the configuration file (for example: .zshrc, .bashrc, etc.), and confirm that the configuration file has been used correctly.
