### ISSUE TITLE
RegionId vs region

### ISSUE THREAD

**Issue by robertvolkmann** [aliyun/aliyun-cli#313]
I'm confused about the unexpected behaviour of the parameters `--RegionId` and `--region` .

Examples:
1. The command `aliyun ecs DescribeImages --region=eu-west-1 --RegionId=eu-central-1` does not return any images because the parameter `--region` sets the endpoint to `ecs.eu-west-1.aliyuncs.com` and this endpoint cannot handle the RegionId `eu-central-1`.
2. If the aliyun configuration points to a region different to the parameter '--RegionId' then any ecs command does not work for the same reason as above.

Possible Solution:

- The parameters `--RegionId` and `--region` set the endpoint.
- Either `--RegionId` or `--region` is allowed depending on the operation.

Does this make sense?

**Comment by night556** [comment]
This problem is mainly due to the different behaviors of `region` and `RegionId`. `region` is a CLI parameter that controls the endpoint of the request, while `RegionId` is a server-side parameter.
Regarding the role of `RegionId` and `region`, we are not very clear about how the server handles this aspect. In actual use, it is recommended to use the `region` parameter instead of the `RegionId` parameter.
