### ISSUE TITLE
It is impossible to get RDS DB Instance types

### ISSUE THREAD

**Issue by wojciehm** [aliyun/aliyun-cli#89]
It is not possible to retrieve DB Instance Type from default configured region.

**Comment by night556** [comment]
Please describe your problem in more detail. Maybe you can provide the command you use and the output info when you got this problem.

**Comment by night556** [comment]
> It is not possible to retrieve DB Instance Type from default configured region.

Please describe your problem in more detail. Maybe you can provide the command you use and the output info when you got this problem.

**Comment by wojciehm** [comment]
When you want to create a RDS using aliyun CLI you need to specify several parameters:
`aliyun rds CreateDBInstance`
```ERROR: required parameters not assigned:
- --Engine
- --EngineVersion
- --DBInstanceClass
- --DBInstanceStorage
- --DBInstanceNetType
- --SecurityIPList
- --PayType
```
`aliyun rds DescribeDBInstances` gives an empty response. 
`{"Items":{"DBInstance":[]},"TotalRecordCount":0,"PageNumber":1,"RequestId":"99884C63-5061-4713-B9E5-9BD61DB23424","PageRecordCount":0}`

**Comment by night556** [comment]
> When you want to create a RDS using aliyun CLI you need to specify several parameters:
> `aliyun rds CreateDBInstance`
> 
> ```
> - --Engine
> - --EngineVersion
> - --DBInstanceClass
> - --DBInstanceStorage
> - --DBInstanceNetType
> - --SecurityIPList
> - --PayType
> ```
> `aliyun rds DescribeDBInstances` gives an empty response.
> `{"Items":{"DBInstance":[]},"TotalRecordCount":0,"PageNumber":1,"RequestId":"99884C63-5061-4713-B9E5-9BD61DB23424","PageRecordCount":0}`

Hi, in order to reproduce your problem,  I first ran command `aliyun rds CreateDBInstance `  to create an instance, and then I ran command `aliyun rds DescribeDBInstances`, but the result is different with yours, the result contains the DBInstance I just created. And my cli tool version is 3.0.10, so I recommand that you upgrade to the lastest version and try again.
Thank you for your attention to AliCloud CLI Project!
